// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4FRBrxZlatOcvWgwVdghInn5Vmn6tV-E',
    appId: '1:754227138441:web:47bd57fb336a2f74279b58',
    messagingSenderId: '754227138441',
    projectId: 'todo-app-45974',
    authDomain: 'todo-app-45974.firebaseapp.com',
    storageBucket: 'todo-app-45974.appspot.com',
    measurementId: 'G-PLXHV8VF95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnHihLGljKXXAlZe4S5JKAIixACmaFxWA',
    appId: '1:754227138441:android:f0b5c0c4ba0e6939279b58',
    messagingSenderId: '754227138441',
    projectId: 'todo-app-45974',
    storageBucket: 'todo-app-45974.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlv5aJLrNUsRstLhfjCUPeHpUvTBtQAO8',
    appId: '1:754227138441:ios:64737ecd37d27c9f279b58',
    messagingSenderId: '754227138441',
    projectId: 'todo-app-45974',
    storageBucket: 'todo-app-45974.appspot.com',
    iosClientId: '754227138441-7ghv8ul6r0npgacce376906g948i36rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlv5aJLrNUsRstLhfjCUPeHpUvTBtQAO8',
    appId: '1:754227138441:ios:64737ecd37d27c9f279b58',
    messagingSenderId: '754227138441',
    projectId: 'todo-app-45974',
    storageBucket: 'todo-app-45974.appspot.com',
    iosClientId: '754227138441-7ghv8ul6r0npgacce376906g948i36rr.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
